platform :ios, '6.1'

# Set the pod location to a git repo:
pod 'BCOVPlayerSDK', :git => 'git@bithub.brightcove.com:videocloud/ios-videocloud.git'
pod "BCOVIMA", :git => 'git@bithub.brightcove.com:videocloud/ios-ima.git'

# to a git repo with a specific branch:
#pod 'BCOVPlayerSDK', :git => 'git@bithub.brightcove.com:jwhisenant/ios-videocloud.git', :branch => 'sdk-157'

# Or to a local path:
#pod 'BCOVPlayerSDK', :path => '/Users/jwhisenant/work/appscience/sdks/ios-videocloud'


#target 'BCOVPlayerSDK-specs' do
#    pod 'Kiwi'
#    pod 'Nocilla'
#end

